export type Aluno = {
  period_id: number | null;
  classroom_id: number | null;
  id: number;
  name: string;
  cpf: string;
  rg: string | null;
  data_nascimento: string;
  nome_pai: string | null;
  nome_mae: string;
  genero: string | null;
  deficiencia: string;
  logradouro: string;
  numero: string;
  bairro: string;
  complemento: string | null;
  cidade: string;
  estado: string;
  telefone: string | null;
  celular: string;
  email: string;
  matricula: string;
  turma: string | null;
  status: boolean | 0 | 1;
};

export type AlunoPayload = {
  period_id?: number;
  classroom_id?: number | null;
  name: string;
  cpf?: string;
  rg?: string;
  data_nascimento?: string;
  nome_pai?: string | null;
  nome_mae: string;
  genero?: string | null;
  deficiencia: string;
  logradouro: string;
  numero?: string;
  bairro: string;
  complemento?: string | null;
  cidade: string;
  estado: string;
  telefone?: string | null;
  celular: string;
  email?: string;
  matricula?: string;
  status?: boolean;
  password?: string;
};
