export type Professor = {
  id_user: number;
  name: string;
  cpf: string;
  rg: string;
  data_nascimento: string;
  nome_pai: string | null;
  nome_mae: string;
  genero: string | null;
  deficiencia: string;
  logradouro: string;
  numero: string;
  bairro: string;
  complemento: string | null;
  cidade: string;
  estado: string;
  telefone: string | null;
  celular: string;
  email: string;
  id_professor: number;
  matricula_adpm: string;
  codigo_disciplina: string;
};

export type ProfessorPayload = {
  name?: string;
  cpf?: string;
  rg?: string;
  data_nascimento?: string;
  nome_pai?: string | null;
  nome_mae?: string;
  genero?: string | null;
  deficiencia?: string;
  logradouro?: string;
  numero?: string | null;
  bairro?: string;
  complemento?: string | null;
  cidade?: string;
  estado?: string;
  telefone?: string | null;
  celular?: string;
  email?: string;
  password?: string;
  matricula_adpm?: string;
  codigo_disciplina?: string;
};
